package voxSpell.gui;

import java.io.File;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

import voxSpell.quiz.Settings;

import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;

//======================================================
//Source code generated by jvider v1.8.1 UNREGISTERED version.
//http://www.jvider.com/
// Modified significantly by atag549
//======================================================
/**
 * Class developed for Assignment 3 of Softeng 206
 * User interface for changing the voxSpell voice settings
 * Avaiable classes displayed are read from the user's system
 * 
 * @author atag549
 *
 */
public class SettingsScreen{
	JPanel _panel;
	JLabel _voiceLabel;
	JComboBox<String> _chooseVoice;
	JLabel _speedLabel;
	JComboBox<String> _chooseSpeed;
	JButton _submitVoice;
	JButton _submitSpeed;
	JButton _home;
	public SettingsScreen() {

		_panel = new JPanel();
		_panel.setPreferredSize(GUI.getFrameSize());
		_panel.setBorder(BorderFactory.createTitledBorder("Settings"));
		GridBagLayout gb_panel = new GridBagLayout();
		GridBagConstraints gbc_panel = new GridBagConstraints();
		_panel.setLayout(gb_panel);
		
		_voiceLabel = new JLabel("Choose your voice to use and submit.");
		_voiceLabel.setFont(GUI.TITLE_FONT);
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 0;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.VERTICAL;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 1;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_voiceLabel, gbc_panel);
		_panel.add(_voiceLabel);

		//Get the names of folders dictating available voices
		//Code modified from: http://stackoverflow.com/questions/5694385/getting-the-filenames-of-all-files-in-a-folder
		File pathToVoices = new File("/usr/share/festival/voices/english");
		File[] listOfVoices = pathToVoices.listFiles();
		//Create a model for JComboBox to select voice
		DefaultComboBoxModel<String> selectModel = new DefaultComboBoxModel<String>();
		for (File i : listOfVoices) {
			selectModel.addElement(i.getName());
		}
		_chooseVoice = new JComboBox<String>(selectModel);
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 1;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_chooseVoice, gbc_panel);
		_panel.add(_chooseVoice);
		_chooseVoice.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Settings.getInstance().saySampleVoicePhrase((String)_chooseVoice.getSelectedItem());
			}
		});

		/*_speedLabel = new JLabel("Change Voice Speed");
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 4;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 1;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_speedLabel, gbc_panel);
		_panel.add(_speedLabel);

		String []datacombo1 = {"Chocolate","Ice Cream","Apple Pie"};
		_chooseSpeed = new JComboBox<String>(datacombo1);
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 5;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 2;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_chooseSpeed, gbc_panel);
		_panel.add(_chooseSpeed);*/

		_submitVoice = new JButton("Submit Voice Change");
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 2;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_submitVoice, gbc_panel);
		_panel.add(_submitVoice);
		_submitVoice.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Settings.getInstance().setVoice((String)_chooseVoice.getSelectedItem());
				JOptionPane.showMessageDialog(null, "Your voice has successfully been changed to " + (String)_chooseVoice.getSelectedItem(), "Changed Voice", JOptionPane.INFORMATION_MESSAGE);
			}
		});

		/*_submitSpeed = new JButton("Submit Speed Change");
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 7;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_submitSpeed, gbc_panel);
		_panel.add(_submitSpeed);*/

		_home = new JButton("Go to Main Menu");
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 18;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 2;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_home, gbc_panel);
		_home.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				new WelcomeScreen();
			}
		});
		_panel.add(_home);
		
		GUI.getInstance().getFrame().setContentPane(_panel);
		GUI.getInstance().getFrame().pack();
		GUI.getInstance().getFrame().setVisible(true);
	} 
} 
