package voxSpell.gui;

//======================================================
//Source code generated by jvider v1.8.1 UNREGISTERED version.
//	Then almost entirely edited because the layout kept turning out wrong by Aimee Tagle 14/09/16
//http://www.jvider.com/
//======================================================
import javax.swing.JPanel;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.swing.JLabel;
import javax.swing.JButton;
public class WelcomeScreen {

	private JPanel _panel;
	private JLabel _title;
	private JLabel _pleaseSelect;
	private JButton _newQuiz;
	private JButton _review;
	private JButton _viewStats;
	private JButton _clearStats;
	private JButton _settings;
	private JLabel _level;
	private JLabel _image;

	public WelcomeScreen() {

		_panel = new JPanel();
		_panel.setPreferredSize(GUI.getFrameSize());
		_panel.setBorder(BorderFactory.createTitledBorder("Main Menu"));
		GridBagLayout gb_panel = new GridBagLayout();
		GridBagConstraints gbc_panel = new GridBagConstraints();
		_panel.setLayout(gb_panel);

		_title = new JLabel("Welcome to voxSpell");
		_title.setFont(GUI.TITLE_FONT);
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 0;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.VERTICAL;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 1;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_title, gbc_panel);
		_panel.add(_title);

		_pleaseSelect = new JLabel("Select an option below");
		gbc_panel.gridx = 0;
		gbc_panel.gridy =10;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.VERTICAL;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 1;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_pleaseSelect, gbc_panel);
		_panel.add(_pleaseSelect);

		_newQuiz = new JButton("New Quiz");
		_newQuiz.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				new QuizScreen("New Quiz", false);
			}
		});
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 11;
		gbc_panel.gridwidth = 4;
		gbc_panel.gridheight = 3;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_newQuiz, gbc_panel);
		_panel.add(_newQuiz);

		_review = new JButton("Review");
		_review.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				new QuizScreen("Review", true);
			}
		});
		gbc_panel.gridx = 4;
		gbc_panel.gridy = 11;
		gbc_panel.gridwidth = 4;
		gbc_panel.gridheight = 3;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.CENTER;
		gb_panel.setConstraints(_review, gbc_panel);
		_panel.add(_review);

		_viewStats = new JButton("View Stats");
		gbc_panel.gridx = 8;
		gbc_panel.gridy = 11;
		gbc_panel.gridwidth = 4;
		gbc_panel.gridheight = 3;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_viewStats, gbc_panel);
		_panel.add(_viewStats);

		_clearStats = new JButton("Clear Stats");
		gbc_panel.gridx = 12;
		gbc_panel.gridy = 11;
		gbc_panel.gridwidth = 4;
		gbc_panel.gridheight = 3;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_clearStats, gbc_panel);
		_panel.add(_clearStats);

		_settings = new JButton("Settings");
		_settings.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				new SettingsScreen();
			}
		});

		gbc_panel.gridx = 16;
		gbc_panel.gridy = 11;
		gbc_panel.gridwidth = 4;
		gbc_panel.gridheight = 3;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 0;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_settings, gbc_panel);
		_panel.add(_settings);

		//From http://stackoverflow.com/questions/299495/how-to-add-an-image-to-a-jpanel
		BufferedImage myPicture;
		try {
			_image = new JLabel("             ");
			myPicture = ImageIO.read(new File("./src/nasser_concept-mini.png"));
			JLabel picLabel = new JLabel(new ImageIcon(myPicture));
			_image.add(picLabel);
			GridBagLayout gb_image = new GridBagLayout();
			_image.setLayout(gb_image);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		gbc_panel.gridx = 15;
		gbc_panel.gridy =0;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 30;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 1;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_image, gbc_panel);
		_panel.add(_image);

		_level = new JLabel("You are on Level " + (GUI.getLevel()+1));
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 8;
		gbc_panel.gridwidth = 20;
		gbc_panel.gridheight = 1;
		gbc_panel.fill = GridBagConstraints.VERTICAL;
		gbc_panel.weightx = 1;
		gbc_panel.weighty = 1;
		gbc_panel.anchor = GridBagConstraints.NORTH;
		gb_panel.setConstraints(_level, gbc_panel);
		_panel.add(_level);
		
		GUI.getInstance().getFrame().setContentPane(_panel);
		GUI.getInstance().getFrame().pack();
		GUI.getInstance().getFrame().setVisible(true);
	} 
} 